language: php

php:
    - 7.1

sudo: false

matrix:
    allow_failures:
        - php: hhvm
        
before_script:
    - travis_retry composer self-update
    - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction
script:
    - php vendor/bin/phpunit test